version: '3.8'

services:
    backend: 
      build: ./server
      ports: 
        - "3000:3000"
      environment: 
        - PORT=3000
        - SUPABASE_URL={SUPABASE_URL}
        - SUPABASE_KEY={SUPABASE_KEY}

    frontend:
      build: ./client
      ports: 
        - "5173:5173"
